# Generated by Django 6.0.5 on 2026-06-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tin_nhan', models.TextField()),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('sdt', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
